# Generated by Django 3.0 on 2023-10-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
