# Generated by Django 3.0 on 2023-10-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'created'), ('NO_ROBOT_IN_STOCK', 'no_robot_in_stock'), ('READY', 'ready')], default='CREATED', max_length=17, verbose_name='Статус заказа'),
        ),
    ]
